name: Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build-doc:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build documentation
        run: |
          set -x
          set -e
          cargo doc --no-deps
      - name: Reroute index.html
        run: |
          echo \
            "<meta http-equiv=\"refresh\" content=\"0; url=mandelbrot\">" \
             > \
             target/doc/index.html
      - name: Make thumbnail
        run: |
          while true
          do
            if cargo run \
              --release \
              -- \
              --seed=$RANDOM$RANDOM \
              --grid_size=5.e-6 \
              --fname=image.ppm \
              --width=1280 \
              --height=640 ; then
              break
            fi
          done
      - name: Convert ppm to jpg
        run: |
          sudo apt-get -y update && \
          sudo apt-get -y install imagemagick
          convert image.ppm image.jpg
      - name: Put thumbnail under static.files
        run: |
          mv image.jpg target/doc/static.files/image.jpg
      - name: Upload HTML artifacts
        uses: actions/upload-artifact@main
        with:
          name: DocHTML
          path: target/doc

  deploy-doc:
    name: Deploy documentation
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build-doc]
    steps:
      - name: Download HTML artifacts
        uses: actions/download-artifact@main
        with:
          name: DocHTML
          path: docs
      - name: Setup GitHub Pages
        uses: actions/configure-pages@main
      - name: Upload HTML
        uses: actions/upload-pages-artifact@main
        with:
          path: docs
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main

